# Advanced Configuration File for Fiber Optics Neural Network
# This file allows tweaking every variable, numeric, parameter, weight etc.
# "I would also like the original program to no longer use commands instead 
# I want the entire program to run from a config file"

# System Settings
system:
  # Device configuration
  device: "auto"  # auto, cuda, cpu
  gpu_id: 0
  num_workers: 4
  seed: 42
  
  # Logging configuration
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file_path: "logs/fiber_optics.log"
  verbose_logging: true
  
  # Paths
  data_path: "data/fiber_optics"
  tensorized_data_path: "data/tensorized"
  reference_data_path: "data/references"
  checkpoints_path: "checkpoints"
  results_path: "results"

# Model Architecture Configuration
model:
  # Architecture type
  architecture: "advanced"  # basic, advanced, efficient
  
  # Basic architecture parameters
  input_channels: 3
  base_channels: 64
  num_blocks: [2, 2, 2, 2]  # Blocks at each scale
  
  # Advanced components
  use_se_blocks: true
  se_reduction: 16
  use_deformable_conv: true
  use_cbam: true
  use_efficient_channel_attention: false
  
  # Adaptive computation
  use_adaptive_computation: true
  adaptive_threshold: 0.95
  max_computation_steps: 10
  
  # Number of classes/regions
  num_classes: 3  # core, cladding, ferrule
  num_reference_embeddings: 1000
  embedding_dim: 256

# Equation Parameters (I=Ax1+Bx2+Cx3...=S(R))
equation:
  # Initial coefficients
  coefficients:
    A: 1.0  # Reference similarity weight
    B: 1.0  # Trend adherence weight
    C: 1.0  # Inverse anomaly score weight
    D: 1.0  # Segmentation confidence weight
    E: 1.0  # Reconstruction similarity weight
  
  # Coefficient bounds
  min_coefficient: -2.0
  max_coefficient: 2.0
  
  # Evolution strategy for coefficients
  use_evolution: true
  evolution_interval: 100  # Apply every N steps
  population_size: 20
  evolution_sigma: 0.1
  evolution_learning_rate: 0.01

# Optimizer Configuration
optimizer:
  # Optimizer type
  type: "sam_lookahead"  # adam, sgd, sam, lookahead, sam_lookahead, hybrid
  
  # Base optimizer parameters
  learning_rate: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1.0e-8
  
  # SAM parameters
  sam_rho: 0.05
  sam_adaptive: true
  
  # Lookahead parameters
  lookahead_k: 5
  lookahead_alpha: 0.5
  lookahead_pullback: "none"  # none, pullback
  
  # Learning rate schedule
  scheduler:
    type: "reduce_on_plateau"  # cosine, step, exponential, reduce_on_plateau
    patience: 5
    factor: 0.5
    min_lr: 1.0e-6
  
  # Parameter-specific learning rates
  param_groups:
    feature_extractor: 1.0  # Multiplier of base LR
    segmentation: 0.5
    reference_embeddings: 0.1
    decoder: 0.5
    equation_parameters: 0.01

# Loss Function Configuration
loss:
  # Loss weights
  weights:
    segmentation: 0.25
    anomaly: 0.20
    contrastive: 0.15
    perceptual: 0.15
    wasserstein: 0.10
    reconstruction: 0.15
  
  # Focal loss parameters
  focal_loss:
    segmentation_alpha: 0.25
    segmentation_gamma: 2.0
    anomaly_alpha: 0.75  # Higher for rare defects
    anomaly_gamma: 3.0
  
  # Contrastive loss parameters
  contrastive_loss:
    temperature: 0.07
    normalize: true
  
  # Wasserstein loss parameters
  wasserstein_loss:
    p: 1  # 1-Wasserstein or 2-Wasserstein
    epsilon: 0.1
    max_iter: 100
  
  # Perceptual loss parameters
  perceptual_loss:
    network: "vgg16"  # vgg16, vgg19, alex
    layers: [3, 8, 15, 22, 29]
    use_spatial: false

# Similarity Metrics Configuration
similarity:
  # Similarity threshold
  threshold: 0.7  # "must achieve over .7"
  
  # LPIPS parameters
  lpips:
    network: "vgg16"
    use_dropout: true
    spatial: false
  
  # Optimal transport parameters
  optimal_transport:
    epsilon: 0.1
    max_iter: 100
    metric: "euclidean"  # euclidean, cosine, manhattan
  
  # SSIM parameters
  ssim:
    window_size: 11
    use_edges: true
    multi_scale: true
  
  # Combined metric weights
  combination_weights:
    lpips: 0.4
    ssim: 0.3
    optimal_transport: 0.3

# Training Configuration
training:
  # Basic training parameters
  num_epochs: 100
  batch_size: 16
  validation_split: 0.2
  early_stopping_patience: 10
  
  # Data augmentation
  augmentation:
    enabled: true
    random_rotation: 15  # degrees
    random_scale: [0.9, 1.1]
    random_brightness: 0.1
    random_contrast: 0.1
    horizontal_flip: true
    vertical_flip: true
  
  # Gradient clipping
  gradient_clip_value: 1.0
  gradient_clip_norm: 5.0
  
  # Mixed precision training
  use_amp: true
  amp_opt_level: "O1"  # O0, O1, O2, O3
  
  # Knowledge distillation
  use_distillation: false
  distillation_alpha: 0.7
  distillation_temperature: 4.0
  teacher_model_path: null

# Anomaly Detection Configuration
anomaly:
  # Detection threshold
  threshold: 0.3
  
  # Detection parameters
  min_defect_size: 10  # pixels
  max_defect_size: 1000  # pixels
  
  # Region boundary handling
  ignore_boundary_width: 5  # pixels
  region_transition_tolerance: 0.1
  
  # Defect classification
  defect_types: ["scratch", "contamination", "chip", "crack", "other"]
  confidence_threshold: 0.5

# Feature Extraction Configuration
features:
  # Multi-scale parameters
  scales: [1.0, 0.75, 0.5, 0.25]
  scale_weights: [0.4, 0.3, 0.2, 0.1]
  
  # Gradient calculation
  gradient_kernel_size: 3
  gradient_normalization: true
  
  # Position encoding
  use_position_encoding: true
  position_encoding_dim: 64
  
  # Trend analysis
  trend_window_size: 7
  trend_polynomial_degree: 2

# Real-time Optimization
realtime:
  # Target FPS
  target_fps: 30
  
  # Model compression
  use_pruning: false
  pruning_ratio: 0.3
  
  use_quantization: false
  quantization_backend: "qnnpack"
  
  # Batch processing
  max_batch_size: 8
  dynamic_batching: true
  
  # Caching
  enable_caching: true
  cache_size: 100

# Visualization Configuration
visualization:
  # Display settings
  window_width: 1920
  window_height: 1080
  fps: 60
  
  # UI elements
  show_original: true
  show_segmentation: true
  show_anomaly_map: true
  show_reference_match: true
  show_statistics: true
  show_coefficients: true
  
  # Color maps
  segmentation_colors:
    core: [255, 0, 0]      # Red
    cladding: [0, 255, 0]  # Green
    ferrule: [0, 0, 255]   # Blue
  
  anomaly_colormap: "hot"  # hot, jet, viridis, plasma
  
  # Interactive controls
  enable_parameter_adjustment: true
  parameter_adjustment_step: 0.01
  
  # Export settings
  save_visualizations: true
  visualization_format: "png"  # png, jpg, mp4
  video_codec: "h264"

# Advanced Features (Research-based)
advanced:
  # Gradient Flow Enhancement
  use_gradient_checkpointing: true
  
  # Neural Architecture Search
  use_nas: false
  nas_search_space: "darts"  # darts, enas, pnas
  
  # Meta-learning
  use_maml: false
  maml_inner_steps: 5
  maml_inner_lr: 0.01
  
  # Self-supervised pretraining
  use_self_supervised: false
  ssl_method: "simclr"  # simclr, byol, swav
  
  # Uncertainty estimation
  use_uncertainty: true
  uncertainty_method: "dropout"  # dropout, ensemble, evidential
  dropout_samples: 10
  
  # Continual learning
  use_continual_learning: false
  replay_buffer_size: 1000
  
  # Neural ODE
  use_neural_ode: false
  ode_solver: "dopri5"
  ode_rtol: 1e-3
  ode_atol: 1e-4

# Experimental Features
experimental:
  # Attention mechanisms
  use_cross_attention: true
  use_self_attention: true
  attention_heads: 8
  
  # Graph neural networks
  use_graph_features: false
  graph_hidden_dim: 128
  graph_num_layers: 3
  
  # Transformer backbone
  use_transformer: false
  transformer_depth: 12
  transformer_heads: 12
  transformer_dim: 768
  
  # Diffusion models for anomaly
  use_diffusion: false
  diffusion_steps: 1000
  diffusion_beta_schedule: "linear"

# Performance Monitoring
monitoring:
  # Metrics to track
  track_memory_usage: true
  track_computation_time: true
  track_gradient_norms: true
  
  # Tensorboard
  use_tensorboard: true
  tensorboard_dir: "runs"
  
  # Weights & Biases
  use_wandb: false
  wandb_project: "fiber-optics"
  wandb_entity: null
  
  # Profiling
  enable_profiling: false
  profile_batches: [10, 20]

# Debug Configuration
debug:
  # Debug mode
  enabled: false
  
  # Visualization debugging
  save_intermediate_features: false
  save_gradient_flow: false
  save_attention_maps: false
  
  # Numerical checks
  check_nan: true
  check_inf: true
  
  # Deterministic mode
  deterministic: true
  benchmark: false