# Configuration for the fiber optic defect detection pipeline

# File paths
input_folder: "data/input_images"
output_folder: "data/output"
defect_library_folder: "data/defect_library"

# Image processing parameters
image_size: [512, 512]
blur_kernel_size: [5, 5]
canny_thresholds: [50, 150]

# Zone segmentation parameters
# Radii in microns, will be converted to pixels based on calibration
zone_definitions:
  core: 10
  cladding: 125
  adhesive: 135
  ferrule: 250

# Defect detection parameters
min_defect_area_px: 20
scratch_aspect_ratio_threshold: 3.0
anomaly_threshold_sigma: 3.0

# Clustering parameters
num_clusters: 4

# Real-time analysis parameters
realtime_enabled: false
camera_index: 0
max_fps: 10

# AI model parameters
ai_models:
  segmenter_weights: "models/segmenter_best.pth"
  anomaly_weights: "models/cae_last.pth"
  use_gpu: true
